import { AfterContentInit, ChangeDetectorRef, ElementRef, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor, FormGroupDirective, NgControl, NgForm } from '@angular/forms';
import { DaysOfWeek, DejaDateSelectorComponent } from '../date-selector';
export declare class DejaDatePickerComponent implements OnInit, ControlValueAccessor, AfterContentInit {
    private elementRef;
    private changeDetectorRef;
    _control: NgControl;
    private _parentForm;
    private _parentFormGroup;
    dateMax: Date;
    dateMin: Date;
    dropdownContainerId: string;
    dropdownAlignment: string;
    ownerAlignment: string;
    format: string;
    placeholder: string;
    disableDates: Array<DaysOfWeek | Date>;
    dateSelectorComponent: DejaDateSelectorComponent;
    dateChange: EventEmitter<{}>;
    protected mdHint: any;
    protected mask: any[];
    private inputElementRef;
    private inputValidatorDirective;
    private _showDropDown;
    private keyDownSubscription;
    private _disabled;
    private _time;
    private date;
    private inputModel;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(elementRef: ElementRef, changeDetectorRef: ChangeDetectorRef, _control: NgControl, _parentForm: NgForm, _parentFormGroup: FormGroupDirective);
    ngOnInit(): void;
    private readonly containerElement;
    private showDropDown;
    disabled: boolean | string;
    time: boolean | string;
    close(): void;
    open(): void;
    value: Date;
    writeValue(value: Date): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngAfterContentInit(): void;
    setFocus(): void;
    protected toggleDateSelector(event: Event): boolean;
    protected onDateChange(newDate: Date): void;
    protected updateModel(date: string | Date): void;
    protected reset(): void;
}
